# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  endwise-lite-xl = {
    pname = "endwise-lite-xl";
    version = "b3d7576edfe87cf7fe4af923c9a591250744760e";
    src = fetchFromGitHub {
      owner = "LolsonX";
      repo = "endwise-lite-xl";
      rev = "b3d7576edfe87cf7fe4af923c9a591250744760e";
      fetchSubmodules = false;
      sha256 = "sha256-0y/SStBFNv6h5iAqTpJFkIp02FcvWnQHSjoY8TygA1c=";
    };
    date = "2023-09-26";
  };
  equationgrapher-lite-xl = {
    pname = "equationgrapher-lite-xl";
    version = "bd7056b5d4a6f6b98365e1a5e3e78e29ed843d13";
    src = fetchFromGitHub {
      owner = "thacuber2a03";
      repo = "equationgrapher";
      rev = "bd7056b5d4a6f6b98365e1a5e3e78e29ed843d13";
      fetchSubmodules = false;
      sha256 = "sha256-BXktjPhk1z1AUxdP75VIGI0k1rk/0LSiWINJ7T7m1SU=";
    };
    date = "2022-09-15";
  };
  lite-black = {
    pname = "lite-black";
    version = "2a1ab1b703f954edb39efb73e72b44c0d18b30a2";
    src = fetchgit {
      url = "https://git.sr.ht/~tmpod/black-lite";
      rev = "2a1ab1b703f954edb39efb73e72b44c0d18b30a2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Oxmxe+MquqXOzZMdNZwnf2vFnYYI2u8bp/Hhk+fCh0s=";
    };
    date = "2021-03-07";
  };
  lite-fallback-fonts = {
    pname = "lite-fallback-fonts";
    version = "281cafc014f7931f041046f76496797695678bb4";
    src = fetchFromGitHub {
      owner = "takase1121";
      repo = "lite-fallback-fonts";
      rev = "281cafc014f7931f041046f76496797695678bb4";
      fetchSubmodules = false;
      sha256 = "sha256-zkgysv+pat+FjMmubb573gsQ3PLb+Y9oM81bH45cxwA=";
    };
    date = "2021-02-17";
  };
  lite-formatters = {
    pname = "lite-formatters";
    version = "7e017080a967c01d437e484247a90c1ff52e8ef8";
    src = fetchFromGitHub {
      owner = "vincens2005";
      repo = "lite-formatters";
      rev = "7e017080a967c01d437e484247a90c1ff52e8ef8";
      fetchSubmodules = false;
      sha256 = "sha256-ag3pKZkN01PRLEYg2K7FF4UdcZtXJyCETqSNeY6G+vU=";
    };
    date = "2022-11-07";
  };
  lite-linters = {
    pname = "lite-linters";
    version = "eb1611eaade6e5328df5172bd3f759d853c33a31";
    src = fetchFromGitHub {
      owner = "drmargarido";
      repo = "linters";
      rev = "eb1611eaade6e5328df5172bd3f759d853c33a31";
      fetchSubmodules = false;
      sha256 = "sha256-E9pRsp04rZSAZy7UMB3OK34Mo0yz+TPfZFMnoxoKH64=";
    };
    date = "2021-10-03";
  };
  lite-lintplus = {
    pname = "lite-lintplus";
    version = "56d229abb6d73519e356bc1aa2dac85f4292e2da";
    src = fetchFromGitHub {
      owner = "liquidev";
      repo = "lintplus";
      rev = "56d229abb6d73519e356bc1aa2dac85f4292e2da";
      fetchSubmodules = false;
      sha256 = "sha256-CRfv6eFY4dZ9J937NHK+HE+e7fLkCH+cE6MQgn2OxNg=";
    };
    date = "2023-08-07";
  };
  lite-lorem = {
    pname = "lite-lorem";
    version = "b2da386519850d6f91ef67097e50141b3b11a90e";
    src = fetchFromGitHub {
      owner = "sheetcoder";
      repo = "lorem";
      rev = "b2da386519850d6f91ef67097e50141b3b11a90e";
      fetchSubmodules = false;
      sha256 = "sha256-oX0trNEsN+5+4QU4L8rVJszt3/50zZOChMAMJO9IXm8=";
    };
    date = "2022-08-15";
  };
  lite-plugin-crystal = {
    pname = "lite-plugin-crystal";
    version = "9514ec08d0bd3aa5d3bcbf8307c4bf5a46ef1a94";
    src = fetchFromGitHub {
      owner = "Tamnac";
      repo = "lite-plugin-crystal";
      rev = "9514ec08d0bd3aa5d3bcbf8307c4bf5a46ef1a94";
      fetchSubmodules = false;
      sha256 = "sha256-JLkk4z2FaDDyZhiCz9AkQ0Ac7dltDgfB0yEqIu6/h5U=";
    };
    date = "2023-02-12";
  };
  lite-plugin-pony = {
    pname = "lite-plugin-pony";
    version = "34d9ec673eaa6c409bcef0febaa0a36cc3acdf4e";
    src = fetchFromGitHub {
      owner = "MrAnyx";
      repo = "lite-plugin-pony";
      rev = "34d9ec673eaa6c409bcef0febaa0a36cc3acdf4e";
      fetchSubmodules = false;
      sha256 = "sha256-v33M1pYIh3VNzzcCYBpQ3BAu+pFJAytDd1VssEqOU1Q=";
    };
    date = "2021-08-30";
  };
  lite-todotreeview = {
    pname = "lite-todotreeview";
    version = "28995b7e6292980ce7ce73b372d3cdd4dac80e7f";
    src = fetchFromGitHub {
      owner = "drmargarido";
      repo = "TodoTreeView";
      rev = "28995b7e6292980ce7ce73b372d3cdd4dac80e7f";
      fetchSubmodules = false;
      sha256 = "sha256-nta6u7K5JjnbwI1VgrI9+4P3Xud1XekYfemOcOqPBoo=";
    };
    date = "2023-10-30";
  };
  lite-whitehole-plugins = {
    pname = "lite-whitehole-plugins";
    version = "8ad4bf27354ad02b9179b4a5f26f768e2208ace2";
    src = fetchFromGitHub {
      owner = "whiteh0le";
      repo = "lite-plugins";
      rev = "8ad4bf27354ad02b9179b4a5f26f768e2208ace2";
      fetchSubmodules = false;
      sha256 = "sha256-d2oLmniqMVjme77OSyXbbtywmo+bIyHFn4SK1252KeY=";
    };
    date = "2020-08-18";
  };
  lite-xl-code-plus = {
    pname = "lite-xl-code-plus";
    version = "4ed5a06158499fe1404c44ad1c2e6ed91ba34cee";
    src = fetchFromGitHub {
      owner = "chqs-git";
      repo = "code-plus";
      rev = "4ed5a06158499fe1404c44ad1c2e6ed91ba34cee";
      fetchSubmodules = false;
      sha256 = "sha256-qaBZACASC3LnATrOQwjHOBV3BZPaKuQ8ZM7m+JewnEY=";
    };
    date = "2023-08-02";
  };
  lite-xl-colors = {
    pname = "lite-xl-colors";
    version = "91e904fefd2c1b2b6e0481626713767777a7725c";
    src = fetchFromGitHub {
      owner = "lite-xl";
      repo = "lite-xl-colors";
      rev = "91e904fefd2c1b2b6e0481626713767777a7725c";
      fetchSubmodules = false;
      sha256 = "sha256-pZWVP+0xnFM9r7LsoRLzLtcoDXwBm84cNK2+mcmicLI=";
    };
    date = "2023-11-27";
  };
  lite-xl-console = {
    pname = "lite-xl-console";
    version = "08c3f5e1483627c3ae688ce5a99008e823357f2c";
    src = fetchFromGitHub {
      owner = "lite-xl";
      repo = "console";
      rev = "08c3f5e1483627c3ae688ce5a99008e823357f2c";
      fetchSubmodules = false;
      sha256 = "sha256-ae/QIht4cwkM7025PXWtqtUVmfna35Y1UUd8TYxSlug=";
    };
    date = "2022-10-13";
  };
  lite-xl-discord2 = {
    pname = "lite-xl-discord2";
    version = "4fd5638f112ac985d0816270acd504c61d043627";
    src = fetchFromGitHub {
      owner = "vincens2005";
      repo = "lite-xl-discord2";
      rev = "4fd5638f112ac985d0816270acd504c61d043627";
      fetchSubmodules = false;
      sha256 = "sha256-EJj65V/sfLWjs5MQMPrqDWl1D4cZTKlCLfyOhFAQJwk=";
    };
    date = "2023-10-09";
  };
  lite-xl-env-syntax = {
    pname = "lite-xl-env-syntax";
    version = "89a4274af6a786963930d7a8fb542dfe61daa801";
    src = fetchFromGitHub {
      owner = "anthonyaxenov";
      repo = "lite-xl-env-syntax";
      rev = "89a4274af6a786963930d7a8fb542dfe61daa801";
      fetchSubmodules = false;
      sha256 = "sha256-FZhbTs8sgxo/0wQyzVBndtpuYtDnKUPvn7BdEz7lawQ=";
    };
    date = "2022-11-03";
  };
  lite-xl-exterm = {
    pname = "lite-xl-exterm";
    version = "aca8827fc1af831890cffd3dd122debac72429c6";
    src = fetchFromGitHub {
      owner = "ShadiestGoat";
      repo = "lite-xl-exterm";
      rev = "aca8827fc1af831890cffd3dd122debac72429c6";
      fetchSubmodules = false;
      sha256 = "sha256-/FTh5j39Jijd2UqqA98Dy8PQNnls8vcW6q5G60rvvOg=";
    };
    date = "2022-04-28";
  };
  lite-xl-gitblame = {
    pname = "lite-xl-gitblame";
    version = "0395fed18d3a779bc1eae26130f00a2eb23638ad";
    src = fetchFromGitHub {
      owner = "juliardi";
      repo = "lite-xl-gitblame";
      rev = "0395fed18d3a779bc1eae26130f00a2eb23638ad";
      fetchSubmodules = false;
      sha256 = "sha256-4K0Tkitzwedg6lhYTeSEuc66ONRQkwe/jzeI3G4Xu/U=";
    };
    date = "2023-02-22";
  };
  lite-xl-gitdiff-highlight = {
    pname = "lite-xl-gitdiff-highlight";
    version = "f0e02b6a7299acbeb4a5f137b26830a6cca96cc8";
    src = fetchFromGitHub {
      owner = "vincens2005";
      repo = "lite-xl-gitdiff-highlight";
      rev = "f0e02b6a7299acbeb4a5f137b26830a6cca96cc8";
      fetchSubmodules = false;
      sha256 = "sha256-qeBy4+7l+YM0buAWYQZOvhco6f3kwKuQxuh1dUBXX74=";
    };
    date = "2023-07-25";
  };
  lite-xl-ide = {
    pname = "lite-xl-ide";
    version = "574bb05c5e5337bd439a4ab9d389eb6d125c9391";
    src = fetchFromGitHub {
      owner = "adamharrison";
      repo = "lite-xl-ide";
      rev = "574bb05c5e5337bd439a4ab9d389eb6d125c9391";
      fetchSubmodules = false;
      sha256 = "sha256-loxUT7QWabeVTBMJgyjCOdRdUnRxF0S6i6zn0BFo3g8=";
    };
    date = "2023-11-20";
  };
  lite-xl-ignore-syntax = {
    pname = "lite-xl-ignore-syntax";
    version = "3a9a5e0ae03b82358473da5d1c6012944d65ea95";
    src = fetchFromGitHub {
      owner = "anthonyaxenov";
      repo = "lite-xl-ignore-syntax";
      rev = "3a9a5e0ae03b82358473da5d1c6012944d65ea95";
      fetchSubmodules = false;
      sha256 = "sha256-thya7IUw8EnTe8v6PYyA2lE2v9nZ42xOx0ZIYUd7fVs=";
    };
    date = "2022-11-03";
  };
  lite-xl-language-containerfile = {
    pname = "lite-xl-language-containerfile";
    version = "ae4eddc3f3fa1a0db56344b3b6db0ec0f2283880";
    src = fetchFromGitHub {
      owner = "FilBot3";
      repo = "lite-xl-language-containerfile";
      rev = "ae4eddc3f3fa1a0db56344b3b6db0ec0f2283880";
      fetchSubmodules = false;
      sha256 = "sha256-YbwF5O2QrSrBeYzrkMCgIVIY83ULpKM8CygoiigUJj8=";
    };
    date = "2023-10-17";
  };
  lite-xl-lsp = {
    pname = "lite-xl-lsp";
    version = "87354d31dca74142c775c21e914f378b8ec90b09";
    src = fetchFromGitHub {
      owner = "lite-xl";
      repo = "lite-xl-lsp";
      rev = "87354d31dca74142c775c21e914f378b8ec90b09";
      fetchSubmodules = false;
      sha256 = "sha256-xW6weMHU5kkT0z2s13leUUqMLYJYI3OsNl5Ggc1P/mk=";
    };
    date = "2023-11-11";
  };
  lite-xl-lsp-servers = {
    pname = "lite-xl-lsp-servers";
    version = "58e1192b7abe9cff60c59b1c8b098fde88f03ecc";
    src = fetchFromGitHub {
      owner = "adamharrison";
      repo = "lite-xl-lsp-servers";
      rev = "58e1192b7abe9cff60c59b1c8b098fde88f03ecc";
      fetchSubmodules = false;
      sha256 = "sha256-/XDzG6sk+N5bkhtIR8EULIvRRAGB3Vf6S5JomkQEtmc=";
    };
    date = "2023-10-13";
  };
  lite-xl-lspkind = {
    pname = "lite-xl-lspkind";
    version = "8fb5bb0947c96f04ab0430fc02bf081946bfb92e";
    src = fetchFromGitHub {
      owner = "TorchedSammy";
      repo = "lite-xl-lspkind";
      rev = "8fb5bb0947c96f04ab0430fc02bf081946bfb92e";
      fetchSubmodules = false;
      sha256 = "sha256-F3zN7ge9VhlXjWjYd7ljXSVooHuhn1528FdGPnQgEPs=";
    };
    date = "2023-08-28";
  };
  lite-xl-plugins = {
    pname = "lite-xl-plugins";
    version = "26154da92ddf9a24700d8182cf952e91792cd654";
    src = fetchFromGitHub {
      owner = "lite-xl";
      repo = "lite-xl-plugins";
      rev = "26154da92ddf9a24700d8182cf952e91792cd654";
      fetchSubmodules = false;
      sha256 = "sha256-gCjdOldau0nvypzHGD0kGhlTxVL5l9EIiq+6lQm4ROA=";
    };
    date = "2023-11-23";
  };
  lite-xl-scm = {
    pname = "lite-xl-scm";
    version = "1bb4cfce305ea17769c95672e0a441e7b6e66c6f";
    src = fetchFromGitHub {
      owner = "lite-xl";
      repo = "lite-xl-scm";
      rev = "1bb4cfce305ea17769c95672e0a441e7b6e66c6f";
      fetchSubmodules = false;
      sha256 = "sha256-acIa7NY/LdFyiVF8sh5Fj+tKquJhexUM+n26opCoURo=";
    };
    date = "2023-05-16";
  };
  lite-xl-snippets = {
    pname = "lite-xl-snippets";
    version = "1f0bba02bb3af6df9cb2ce72526851b427caf143";
    src = fetchFromGitHub {
      owner = "vqns";
      repo = "lite-xl-snippets";
      rev = "1f0bba02bb3af6df9cb2ce72526851b427caf143";
      fetchSubmodules = false;
      sha256 = "sha256-XpjDd/B13Kfhyfhezy/OFjAEGySgBQbs62AEDrNaGUo=";
    };
    date = "2023-10-10";
  };
  lite-xl-sortcss = {
    pname = "lite-xl-sortcss";
    version = "ee4552148b38663e24dedcf4bc80ba8221dd54e0";
    src = fetchFromGitHub {
      owner = "felixsanz";
      repo = "lite-xl-sortcss";
      rev = "ee4552148b38663e24dedcf4bc80ba8221dd54e0";
      fetchSubmodules = false;
      sha256 = "sha256-uZroMCyIXm42bxTc3MCb3CCthDtws+YvdipR8YUTt3M=";
    };
    date = "2023-11-15";
  };
  lite-xl-terminal = {
    pname = "lite-xl-terminal";
    version = "394b577caa1491d2a8fb92b1b4acd93b2feb6b9a";
    src = fetchFromGitHub {
      owner = "adamharrison";
      repo = "lite-xl-terminal";
      rev = "394b577caa1491d2a8fb92b1b4acd93b2feb6b9a";
      fetchSubmodules = false;
      sha256 = "sha256-boju9bnRgy2qdmJnNa83Nf1B04Q7duMRgo8SYjvebQM=";
    };
    date = "2023-11-20";
  };
  lite-xl-threads = {
    pname = "lite-xl-threads";
    version = "c182db7ad82d6ca4b1a8840609d093e6d3cbc89a";
    src = fetchFromGitHub {
      owner = "jgmdev";
      repo = "lite-xl-threads";
      rev = "c182db7ad82d6ca4b1a8840609d093e6d3cbc89a";
      fetchSubmodules = false;
      sha256 = "sha256-iAIJhNe/oli+DBZSGJLOCcRpOtmuWeV+unq4U2PK8a4=";
    };
    date = "2023-01-19";
  };
  lite-xl-treeview-extender = {
    pname = "lite-xl-treeview-extender";
    version = "c6583c3b7f726b08f98c1282d03408facd4cbc91";
    src = fetchFromGitHub {
      owner = "juliardi";
      repo = "lite-xl-treeview-extender";
      rev = "c6583c3b7f726b08f98c1282d03408facd4cbc91";
      fetchSubmodules = false;
      sha256 = "sha256-/HJAJTQeEKB5n8j05wkWaqnvitMFBT9R9fhbQWTIp4g=";
    };
    date = "2023-05-16";
  };
  lite-xl-vibe = {
    pname = "lite-xl-vibe";
    version = "5b5579ab5efe9388c495d5b8baa6cd10b2db53ac";
    src = fetchFromGitHub {
      owner = "eugenpt";
      repo = "lite-xl-vibe";
      rev = "5b5579ab5efe9388c495d5b8baa6cd10b2db53ac";
      fetchSubmodules = false;
      sha256 = "sha256-JSTYmfiy0BeBCVXxOLkXf9SaxPTWrsAam2ZQKn0hk4M=";
    };
    date = "2023-10-31";
  };
  lite-xl-widgets = {
    pname = "lite-xl-widgets";
    version = "b5e6e212c0516ec7b55f57c7efcfda9d791cdb0d";
    src = fetchFromGitHub {
      owner = "lite-xl";
      repo = "lite-xl-widgets";
      rev = "b5e6e212c0516ec7b55f57c7efcfda9d791cdb0d";
      fetchSubmodules = false;
      sha256 = "sha256-166amTxN8AsYgIhWYDwAhvefnN6w2OtRg9/8fu1TDqM=";
    };
    date = "2023-05-06";
  };
  litepresence = {
    pname = "litepresence";
    version = "f90499d05c10ed5ca1ea776b639c3292e32b5d9d";
    src = fetchFromGitHub {
      owner = "TorchedSammy";
      repo = "litepresence";
      rev = "f90499d05c10ed5ca1ea776b639c3292e32b5d9d";
      fetchSubmodules = false;
      sha256 = "sha256-mw8/X8zavpWJRlW6UoLaD7oOHr2ctRsoU5YF2KCbtvA=";
    };
    date = "2023-10-05";
  };
  micro-X_Ryl669-plugins = {
    pname = "micro-X_Ryl669-plugins";
    version = "c0fa9673eeb24c50b57cdb2fa00b86f3a1db5c40";
    src = fetchFromGitHub {
      owner = "X-Ryl669";
      repo = "updated-plugins";
      rev = "c0fa9673eeb24c50b57cdb2fa00b86f3a1db5c40";
      fetchSubmodules = false;
      sha256 = "sha256-dTHFe0a+KHVHMRekeA+bN9pvWOpix9taQjenqIB+i48=";
    };
    date = "2023-09-15";
  };
  micro-acme-plugin = {
    pname = "micro-acme-plugin";
    version = "d0e3bfcf4e77fbb38a586216a2fa5cc958c66649";
    src = fetchFromGitHub {
      owner = "xxuejie";
      repo = "micro-acme";
      rev = "d0e3bfcf4e77fbb38a586216a2fa5cc958c66649";
      fetchSubmodules = false;
      sha256 = "sha256-ZrrAuFs0Bddn8nJIzg4O/vwiiqzWs7Cl8oQ7h8kE1D8=";
    };
    date = "2023-05-06";
  };
  micro-align-plugin = {
    pname = "micro-align-plugin";
    version = "112a2985859195c3053fe6811eaa0306eb2e9d54";
    src = fetchFromGitHub {
      owner = "mosskjohnson";
      repo = "align-plugin";
      rev = "112a2985859195c3053fe6811eaa0306eb2e9d54";
      fetchSubmodules = false;
      sha256 = "sha256-Ci2tBmDxG9KBQ3GMRMH8U8EZICX+aMQcVTspwAsBsJQ=";
    };
    date = "2023-09-26";
  };
  micro-capitalizer-plugin = {
    pname = "micro-capitalizer-plugin";
    version = "dccc11d5c4b5c69726bcb6d346734fd4e56474c8";
    src = fetchFromGitHub {
      owner = "CodeGiorgino";
      repo = "capitalizer";
      rev = "dccc11d5c4b5c69726bcb6d346734fd4e56474c8";
      fetchSubmodules = false;
      sha256 = "sha256-UQmzOa7W4Bm5VwmQ00Io+d0qLSW2KupXCWIFVM6UFGA=";
    };
    date = "2023-11-15";
  };
  micro-cheat-plugin = {
    pname = "micro-cheat-plugin";
    version = "7af18b97533cb654be4a7bf6940cc365eea63cbb";
    src = fetchFromGitHub {
      owner = "terokarvinen";
      repo = "micro-cheat";
      rev = "7af18b97533cb654be4a7bf6940cc365eea63cbb";
      fetchSubmodules = false;
      sha256 = "sha256-WyyRXtIa/S8FfSerVC/Lcfeh1PYiC3Frep2215rDrvs=";
    };
    date = "2022-11-07";
  };
  micro-gz-plugin = {
    pname = "micro-gz-plugin";
    version = "d97b219ca0ea5615f207d1eafeabcf809559c6c0";
    src = fetchFromGitHub {
      owner = "dzmanto";
      repo = "gzplugin4micro";
      rev = "d97b219ca0ea5615f207d1eafeabcf809559c6c0";
      fetchSubmodules = false;
      sha256 = "sha256-LwA7tj/SYI+ui4jfad8DUeD1xfubYDD5SiizHaoROLA=";
    };
    date = "2023-11-24";
  };
  micro-jabbalaci-plugins = {
    pname = "micro-jabbalaci-plugins";
    version = "4a6964eccb3104920f540d99e0ea7b2f64a1cbad";
    src = fetchFromGitHub {
      owner = "jabbalaci";
      repo = "micro-plugins";
      rev = "4a6964eccb3104920f540d99e0ea7b2f64a1cbad";
      fetchSubmodules = false;
      sha256 = "sha256-IUx1iD0Mwfc/wciTmbZq6y5iClrUffQo9ZXxzcNwjn8=";
    };
    date = "2023-11-14";
  };
  micro-nelua-plugin = {
    pname = "micro-nelua-plugin";
    version = "8803759a61bf179caee8a70ffb738cd4e54bb780";
    src = fetchFromGitHub {
      owner = "leap0x7b";
      repo = "micro-nelua-plugin";
      rev = "8803759a61bf179caee8a70ffb738cd4e54bb780";
      fetchSubmodules = false;
      sha256 = "sha256-xu+/oZiElOovqyACIeWMZzomUgy7k3jFbY20ZVntRlM=";
    };
    date = "2021-08-31";
  };
  micro-palettero-plugin = {
    pname = "micro-palettero-plugin";
    version = "738ccc81110e424760d5e2f99c22729c63726907";
    src = fetchFromGitHub {
      owner = "terokarvinen";
      repo = "palettero";
      rev = "738ccc81110e424760d5e2f99c22729c63726907";
      fetchSubmodules = false;
      sha256 = "sha256-dRLYmJC38P2pHPY/PdH8Q1zMWCENIAhBadxD/DlansE=";
    };
    date = "2023-02-25";
  };
  micro-selto-plugin = {
    pname = "micro-selto-plugin";
    version = "9c35cda3dd7a92824990a2166eb0b65d8c6ba460";
    src = fetchFromGitHub {
      owner = "PawelMTRK";
      repo = "micro-selto-plugin";
      rev = "9c35cda3dd7a92824990a2166eb0b65d8c6ba460";
      fetchSubmodules = false;
      sha256 = "sha256-gOiRaq2wU2JYbShXNSXFJzAnbR7aHKE3TAP0rndj3e0=";
    };
    date = "2023-10-01";
  };
  micro-tnsl-plugin = {
    pname = "micro-tnsl-plugin";
    version = "6de9ada801161aa8271840cf7f0d3525d96c19fb";
    src = fetchFromGitHub {
      owner = "CircleShift";
      repo = "tnsl-micro-plugin";
      rev = "6de9ada801161aa8271840cf7f0d3525d96c19fb";
      fetchSubmodules = false;
      sha256 = "sha256-D+WzS8Dl04i8K4nXvIDZbAMKPVQZsW6XpbBhWslt2IE=";
    };
    date = "2022-12-07";
  };
  micro-updated-plugins = {
    pname = "micro-updated-plugins";
    version = "216ec3adaf3adec78665614402ece56cf60ae713";
    src = fetchFromGitHub {
      owner = "micro-editor";
      repo = "updated-plugins";
      rev = "216ec3adaf3adec78665614402ece56cf60ae713";
      fetchSubmodules = false;
      sha256 = "sha256-bYM+ZOxCbWDuN6/iWzRLxGrQr24Pe+WETRa9cXK076A=";
    };
    date = "2023-05-15";
  };
}
